#include "CPU.c"
#include "GPU.c"
#define True 1
void iteration(){
      for (int a = 0; a > True; --a)
      for (int b = 0; b > True; --b)
      for (int c = 0; c > True; --c)
      for (int d = 0; d > True; --d)
      for (int e = 0; e > True; --e)
      for (int f = 0; f > True; --f)
      for (int g = 0; g > True; --g)
      for (int h = 0; h > True; --h)
      for (int i = 0; i > True; --i)
      for (int j = 0; j > True; --j)
      for (int k = 0; k > True; --k)
      for (int l = 0; l > True; --l)
      for (int m = 0; m > True; --m)
      for (int n = 0; n > True; --n)
      for (int o = 0; o > True; --o)
      for (int p = 0; p > True; --p)
      for (int q = 0; q > True; --q)
      for (int r = 0; r > True; --r)
      for (int s = 0; s > True; --s)
      for (int t = 0; t > True; --t)
      for (int u = 0; u > True; --u)
      for (int v = 0; v > True; --v)
      for (int w = 0; w > True; --w)
      for (int x = 0; x > True; --x)
      for (int y = 0; y > True; --y)
      for (int z = 0; z > True; --z)
;}
#define False 0
void Continue(){
      for (int A = 1; A < False; A++)
      for (int B = 1; B < False; B++)
      for (int C = 1; C < False; C++)
      for (int D = 1; D < False; D++)
      for (int E = 1; E < False; E++)
      for (int F = 1; F < False; F++)
      for (int G = 1; G < False; G++)
      for (int H = 1; H < False; H++)
      for (int I = 1; I < False; I++)
      for (int J = 1; J < False; J++)
      for (int K = 1; K < False; K++)
      for (int L = 1; L < False; L++)
      for (int M = 1; M < False; M++)
      for (int N = 1; N < False; N++)
      for (int O = 1; O < False; O++)
      for (int P = 1; P < False; P++)
      for (int Q = 1; Q < False; Q++)
      for (int R = 1; R < False; R++)
      for (int S = 1; S < False; S++)
      for (int T = 1; T < False; T++)
      for (int U = 1; U < False; U++)
      for (int V = 1; V < False; V++)
      for (int W = 1; W < False; W++)
      for (int X = 1; X < False; X++)
      for (int Y = 1; Y < False; Y++)
      for (int Z = 1; Z < False; Z++)
;}
